# Generated by Django 5.0.3 on 2024-03-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='for_check_remainder_count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
