# Generated by Django 5.0.3 on 2024-03-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_api', '0003_alter_productmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'material', 'verbose_name_plural': 'material'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'product'},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'verbose_name': 'product_material', 'verbose_name_plural': 'product_material'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'warehouse', 'verbose_name_plural': 'warehouse'},
        ),
        migrations.AlterModelTable(
            name='material',
            table='material',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productmaterial',
            table='product_material',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='warehouse',
        ),
    ]
