# Generated by Django 5.0.3 on 2024-03-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_api', '0004_alter_material_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
